name: Publish to PyPI

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-publish:
    name: Build and publish to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/racgoat
    permissions:
      id-token: write  # Required for trusted publishing
      contents: write  # Required for creating GitHub releases

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - name: Install uv
      uses: astral-sh/setup-uv@v5

    - name: Install dependencies
      run: uv sync

    - name: Run tests
      run: uv run pytest -v

    - name: Build package
      run: uv build

    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        print-hash: true

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        files: dist/*
        generate_release_notes: true
        body: |
          ## RacGoat ${{ github.ref_name }} 🦝🐐

          See [CHANGELOG.md](https://github.com/jjshanks/racgoat/blob/main/CHANGELOG.md) for detailed release notes.

          ### Installation

          ```bash
          uv tool install racgoat==${{ github.ref_name }}
          ```

          Or upgrade from a previous version:

          ```bash
          uv tool upgrade racgoat
          ```
